[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I"
]

[tool.ruff]
line-length = 88
indent-width = 4

# Python target version
target-version = "py311"